### ISSUE TITLE
你所说的这些内容都是真的吗

### ISSUE THREAD

**Issue by Solid-Block** [osurf/osurf#5]

**Comment by wghaotian** [comment]
很明显是假的。别信他。这是法论功你不知道吗？他们就是先激起教徒对政府的反抗，然后给教徒灌输一些完全不科学的东西比如原子可以穿过分子这类愚蠢的玩意儿，最后那群傻x让教徒相信自焚是唯一出路，并利用教徒自杀这类事件抨击我国政党的不民主。。。（相关事件你可以百度一下）真的看这些无聊的狗屁我还他妈不如上B站看100遍Azis-хоп...这群傻叉总他妈以为自己很牛叉的样子想动摇百姓的思想来动摇中共的统治。我就她妈想问这帮狗崽子特么只知道中国这个社会主义国家吗？他妈的有种把这些消息散布到古巴越南朝鲜啊！！笑死！拿共产主义做文章，他妈有本事直接说中国政府啊！他们不敢这么嚣张，说明他们智商没降到零下。。。这群打文章的狗屎想必也不知道自己也被洗脑正走向不归路并被那个李洪傻叉利用。真他妈的可悲。给发文的人提一句，你们教主，就那个李洪傻叉，李洪基佬，他特么自己有病也要上医院的。别他妈傻逼了，www.bilibili.com/av170001 送他们个网址，希望他们迷途知返。
总之现在想在国内通过正常渠道搜到没被污染过的翻墙软件已经很难了。

**Comment by wghaotian** [comment]
送到扫黄打非网上，刻不容缓。

**Comment by Solid-Block** [comment]
osurf这个sb删了不少评论

**Comment by Solid-Block** [comment]
osurf把我们的留言都删了，明显的原形毕露。

在 2017-12-21 22:23:36，"wghaotian" <notifications@github.com> 写道：


很明显是假的。别信他。这是法论功你不知道吗？他们就是先激起教徒对政府的反抗，然后给教徒灌输一些完全不科学的东西比如原子可以穿过分子这类愚蠢的玩意儿，最后那群傻x让教徒相信自焚是唯一出路，并利用教徒自杀这类事件抨击我国政党的不民主。。。（相关事件你可以百度一下）真的看这些无聊的狗屁我还他妈不如上B站看100遍Azis-хоп...这群傻叉总他妈以为自己很牛叉的样子想动摇百姓的思想来动摇中共的统治。我就她妈想问这帮狗崽子特么只知道中国这个社会主义国家吗？他妈的有种把这些消息散布到古巴越南朝鲜啊！！笑死！拿共产主义做文章，他妈有本事直接说中国政府啊！他们不敢这么嚣张，说明他们智商没降到零下。。。这群打文章的狗屎想必也不知道自己也被洗脑正走向不归路并被那个李洪傻叉利用。真他妈的可悲。给发文的人提一句，你们教主，就那个李洪傻叉，李洪基佬，他特么自己有病也要上医院的。别他妈傻逼了，www.bilibili.com/av170001 送他们个网址，希望他们迷途知返。
总之现在想在国内通过正常渠道搜到没被污染过的翻墙软件已经很难了。

**Comment by Solid-Block** [comment]
@wghaotian ：
> 很明显是假的。别信他。这是法论功你不知道吗？他们就是先激起教徒对政府的反抗，然后给教徒灌输一些完全不科学的东西比如原子可以穿过分子这类愚蠢的玩意儿，最后那群傻x让教徒相信自焚是唯一出路，并利用教徒自杀这类事件抨击我国政党的不民主。。。（相关事件你可以百度一下）真的看这些无聊的狗屁我还他妈不如上B站看100遍Azis-хоп...这群傻叉总他妈以为自己很牛叉的样子想动摇百姓的思想来动摇中共的统治。我就她妈想问这帮狗崽子特么只知道中国这个社会主义国家吗？他妈的有种把这些消息散布到古巴越南朝鲜啊！！笑死！拿共产主义做文章，他妈有本事直接说中国政府啊！他们不敢这么嚣张，说明他们智商没降到零下。。。这群打文章的狗屎想必也不知道自己也被洗脑正走向不归路并被那个李洪傻叉利用。真他妈的可悲。给发文的人提一句，你们教主，就那个李洪傻叉，李洪基佬，他特么自己有病也要上医院的。别他妈傻逼了，www.bilibili.com/av170001 送他们个网址，希望他们迷途知返。
总之现在想在国内通过正常渠道搜到没被污染过的翻墙软件已经很难了。

（给大家看一下被删的内容。）

**Comment by Solid-Block** [comment]
共产主义等理论，都是马克思等专家进行过科学鉴定的。至于法轮功是否自焚，我还不能确定，不过我可以确定的是法轮功宣传的方式明显违法。以印纸币为例，公民随便在纸币上乱写乱画都是违法的。又如我曾经看见贴上去的一个“***法好”的字条，妈卖批，就算是宣传“海尔”“百度”或者“华为”，也会被撕掉。而且法轮功明目张胆直截了当地肏政府、肏中共，明显是有政治企图的。真不知道osurf这个别是哪个国家的人。

**Comment by pongfcnkl** [comment]
这群轮子
美国人给钱来黑中国人
